# Generated by Django 5.1.5 on 2025-02-05 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Provincias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_provincia', models.CharField(max_length=65)),
                ('description', models.TextField(blank=True)),
            ],
        ),
    ]
