# Generated by Django 5.1.5 on 2025-02-10 00:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_empleado', models.CharField(max_length=65)),
                ('apellidos_empleado', models.CharField(max_length=250)),
                ('fec_nacimiento', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Rol_Empleado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_rol_empleado', models.CharField(max_length=65)),
                ('detalle_rol', models.TextField(max_length=250, null=True)),
                ('empleado_ID_FK', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Empleados.empleado')),
            ],
        ),
    ]
