# Generated by Django 5.1.5 on 2025-02-10 00:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Empleados', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rol_empleado',
            name='empleado_ID_FK',
        ),
        migrations.AddField(
            model_name='empleado',
            name='rol_empleado_FK',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Empleados.rol_empleado'),
        ),
    ]
