# Generated by Django 5.1.5 on 2025-02-10 00:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Empleados', '0001_initial'),
        ('Productos', '0001_initial'),
        ('Proveedores', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ordenes_Ingreso',
            fields=[
                ('IOrden_ID', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('fec_orden', models.DateTimeField()),
                ('Empleado_ID', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Empleados.empleado')),
                ('Proveedor_ID', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Proveedores.proveedores')),
            ],
        ),
        migrations.CreateModel(
            name='Ordenes_Ingreso_Detalle',
            fields=[
                ('iOrdenDetalle_ID', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('cantidad', models.IntegerField()),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10)),
                ('Orden_ID', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Ordenes_Ingreso.ordenes_ingreso')),
                ('Producto_ID', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Productos.productos')),
            ],
        ),
    ]
