# Generated by Django 5.1.5 on 2025-03-01 05:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ordenes_Ingreso', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordenes_ingreso_detalle',
            name='Orden_ID',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Ordenes_Ingreso.ordenes_ingreso'),
        ),
    ]
