# Generated by Django 5.1.5 on 2025-03-01 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ordenes_Ingreso', '0002_alter_ordenes_ingreso_detalle_orden_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordenes_ingreso_detalle',
            name='Ordenes_IngresoFields',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
