# Generated by Django 5.1.5 on 2025-03-01 07:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Ordenes_Ingreso', '0003_ordenes_ingreso_detalle_ordenes_ingresofields'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ordenes_ingreso_detalle',
            old_name='Orden_ID',
            new_name='IOrden_ID',
        ),
        migrations.RemoveField(
            model_name='ordenes_ingreso_detalle',
            name='Ordenes_IngresoFields',
        ),
    ]
