# Generated by Django 5.1.5 on 2025-03-02 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ordenes_Ingreso', '0004_rename_orden_id_ordenes_ingreso_detalle_iorden_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordenes_ingreso_detalle',
            name='iOrdenDetalle_ID',
            field=models.CharField(max_length=11, primary_key=True, serialize=False),
        ),
    ]
