# Generated by Django 5.1.5 on 2025-03-02 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ordenes_Ingreso', '0005_alter_ordenes_ingreso_detalle_iordendetalle_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordenes_ingreso_detalle',
            name='ordenIngreso',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
