# Generated by Django 5.1.5 on 2025-02-10 00:21

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Numero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(validators=[django.core.validators.MinValueValidator(11111111), django.core.validators.MaxValueValidator(99999999)])),
                ('num_categoria', models.CharField(choices=[('PE', 'Personal'), ('TR', 'Trabajo'), ('CE', 'Celular'), ('CA', 'Casa')], max_length=3)),
                ('num_cod_pais', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(999)])),
            ],
        ),
    ]
