# Generated by Django 5.1.5 on 2025-02-26 05:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('numero', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='numero',
            name='num_categoria',
        ),
    ]
