# Generated by Django 5.1.5 on 2025-02-05 03:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('provincias', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Clientes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_cliente', models.CharField(max_length=65)),
                ('apellidos_cliente', models.CharField(max_length=250)),
                ('direccion', models.TextField(max_length=450, null=True)),
                ('fec_nacimiento', models.DateField()),
                ('correo_electronico', models.EmailField(max_length=254)),
                ('provincia_cliente', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='provincias.provincias')),
            ],
        ),
    ]
