# Generated by Django 5.1.5 on 2025-02-10 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0001_initial'),
        ('numero', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientes',
            name='num_cliente',
            field=models.ManyToManyField(to='numero.numero'),
        ),
    ]
