# Generated by Django 5.1.5 on 2025-02-16 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0002_clientes_num_cliente'),
        ('numero', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientes',
            name='num_cliente',
            field=models.ManyToManyField(null=True, to='numero.numero'),
        ),
    ]
