# Generated by Django 5.1.5 on 2025-02-26 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0003_alter_clientes_num_cliente'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientes',
            name='numero',
            field=models.JSONField(null=True),
        ),
    ]
