# Generated by Django 5.1.5 on 2025-03-01 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0004_clientes_numero'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientes',
            name='numero',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
