# Generated by Django 5.1.5 on 2025-02-10 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Producto_Categorias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_categoria', models.CharField(max_length=50)),
                ('descripcion', models.TextField(null=True)),
            ],
        ),
    ]
