# Generated by Django 5.1.5 on 2025-02-10 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('numero', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Proveedores',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_proveedor', models.CharField(max_length=65)),
                ('nom_contacto', models.CharField(max_length=65, null=True)),
                ('correo_electronico', models.EmailField(max_length=254)),
                ('direccion', models.TextField(max_length=450, null=True)),
                ('num_proveedor', models.ManyToManyField(to='numero.numero')),
            ],
        ),
    ]
