# Generated by Django 5.1.5 on 2025-02-10 00:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Producto_Categorias', '0001_initial'),
        ('Proveedores', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PMarca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_marca', models.CharField(max_length=65)),
                ('descripcion', models.TextField(max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Productos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_producto', models.CharField(max_length=65)),
                ('descripcion', models.TextField(max_length=255, null=True)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=8)),
                ('costo', models.DecimalField(decimal_places=2, max_digits=8)),
                ('codigo_barras', models.CharField(max_length=14)),
                ('fec_vencimiento', models.DateField()),
                ('pCategoria_ID', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Producto_Categorias.producto_categorias')),
                ('pMarca_ID', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Productos.pmarca')),
                ('proveedor_ID', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Proveedores.proveedores')),
            ],
        ),
    ]
