# Generated by Django 5.1.5 on 2025-02-10 00:21

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Empleados', '0001_initial'),
        ('Productos', '0001_initial'),
        ('clientes', '0002_clientes_num_cliente'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ordenes_Egreso',
            fields=[
                ('EOrden_ID', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('fec_orden', models.DateTimeField()),
                ('detalle_orden', models.TextField(max_length=100)),
                ('cliente_ID', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='clientes.clientes')),
                ('empleado_ID', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Empleados.empleado')),
            ],
        ),
        migrations.CreateModel(
            name='EOrdenes_Detalle',
            fields=[
                ('eOrdenDetalle_ID', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('cantidad', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(99)])),
                ('descuento', models.DecimalField(decimal_places=2, max_digits=8)),
                ('producto_ID', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Productos.productos')),
                ('eOrden_ID', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Ordenes_Egreso.ordenes_egreso')),
            ],
        ),
    ]
