# Generated by Django 5.1.5 on 2025-02-16 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ordenes_Egreso', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eordenes_detalle',
            name='descuento',
            field=models.DecimalField(decimal_places=2, max_digits=8, null=True),
        ),
    ]
