# Generated by Django 5.1.5 on 2025-03-03 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ordenes_Egreso', '0002_alter_eordenes_detalle_descuento'),
    ]

    operations = [
        migrations.AddField(
            model_name='eordenes_detalle',
            name='ordenEgreso',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
